version: "3.8"

services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: ../docker/frontend.dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - backend

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - docker/backend.env
    volumes:
      - ./backend:/usr/src/app

  postgres:
    image: postgres:latest
    env_file: docker/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_bridge_network

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - docker/pgadmin.env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - my_bridge_network
    volumes:
      - ./docker/pgadmin_servers.json:/pgadmin4/servers.json

volumes:
  postgres_data:

networks:
  my_bridge_network:
    driver: bridge
