version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    env_file:
      - docker/backend.env

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file: docker/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_bridge_network

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - docker/pgadmin.env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - my_bridge_network
    volumes:
      - ./docker/pgadmin_servers.json:/pgadmin4/servers.json

volumes:
  postgres_data:

networks:
  my_bridge_network:
    driver: bridge
